import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAFMJ3Ev2MIjFQv0JfbLFLWv4QYJ5Eif2fFHHT8zjmcdAAAAJApvIY4KbyG
OAAAAAtzc2gtZWQyNTUxOQAAACAFMJ3Ev2MIjFQv0JfbLFLWv4QYJ5Eif2fFHHT8zjmcdA
AAAEDCgGYcGTuH19EoBV2TLPRuX/VGsTvQ//d5W8ALW4uiDgUwncS/YwiMVC/Ql9ssUta/
hBgnkSJ/Z8UcdPzOOZx0AAAABm15LWtleQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
